language: ruby
rvm:
  - 2.0.0
  - 2.1.4
  - 2.2
before_install:
  - git fetch origin +refs/heads/*:refs/remotes/origin/*
  - git branch --verbose --all
  - git remote --verbose
  - gem install bundler
  - bundle version
script: bundle exec rake ci
sudo: false
cache: bundler
